print("Aws Services.......")
print("Compute Services: Run applications and virtual servers")
print("Amazon EC2")
print("AWS Lambda")
print("AWS Elastic Beanstalk")
print("--------------------------------------------------------------")
print("Storage Services: Save files and backup data safely")
print("Amazon S3")
print("Amazon EBS")
print("Amazon S3 Glacier")

print("--------------------------------------------------------------")
print("Databases: Store structured and unstructured data")
print("Amazon RDS")
print("Amazon DynamoDB")
print("Amazon Aurora")


print("--------------------------------------------------------------")
print("Networking: Connect and secure web traffic")
print("Amazon VPC")
print("Amazon Route 53")
print("Amazon CloudFront")