print("Azure Services.......")
print("Compute Services: Run applications and virtual servers")
print("Azure Virtual Machines")
print("Azure Functions")
print("Azure App Service")
print("--------------------------------------------------------------")
print("Storage Services: Save files and backup data safely")
print("Azure Blob Storage")
print("Azure Disk Storage")
print("Azure Archive Storage")

print("--------------------------------------------------------------")
print("Databases: Store structured and unstructured data")
print("Azure SQL Database")
print("Azure Cosmos DB")
print("Azure Database for PostgreSQL")

print("--------------------------------------------------------------")
print("Networking: Connect and secure web traffic")
print("Azure Virtual Network (VNet)")
print("Azure DNS")
print("Azure Content Delivery Network (CDN)")

print("--------------------------------------------------------------")
print("DevOps Services: Automate, build, test, and deploy applications")
print("Azure Pipelines")
print("Azure Repos")
print("Azure Artifacts")
print("Azure Boards")

print("--------------------------------------------------------------")
print("Infrastructure as Code (IaC): Define and provision resources")
print("Azure Resource Manager (ARM) Templates")
print("Bicep")

print("--------------------------------------------------------------")
print("Monitoring & Logging: Track performance and system health")
print("Azure Monitor")
print("Application Insights")
print("Azure Log Analytics")

print("--------------------------------------------------------------")
print("Configuration & Management: Automate server setup and compliance")
print("Azure Automation")
print("Azure Policy")
print("Azure Automanage")
