print("Aws Services.......")
print("DevOps Services: Automate, build, test, and deploy applications")
print("AWS CodePipeline")
print("AWS CodeBuild")
print("AWS CodeDeploy")
print("AWS CodeCommit")
print("--------------------------------------------------------------")
print("Infrastructure as Code (IaC): Define and provision resources")
print("AWS CloudFormation")
print("AWS Cloud Development Kit (CDK)")
print("--------------------------------------------------------------")
print("Monitoring & Logging: Track performance and system health")
print("Amazon CloudWatch")
print("AWS CloudTrail")
print("AWS X-Ray")
print("--------------------------------------------------------------")
print("Configuration & Management: Automate server setup and compliance")
print("AWS Systems Manager (SSM)")
print("AWS Config")
print("AWS OpsWorks")
