print("Scenario 16: Tracking Down Code Changes via File History")
print("--------------------------------------------------------------")
print("Question: A critical production API endpoint suddenly stopped working. The change happened weeks ago, and nobody remembers who edited that specific block of code or why. How do you find out who modified a specific line in a file and the commit message associated with it?")
print("Answer:")
print("1. Run 'git blame <filename>' to view the file line-by-line. Every line will show the author, commit hash, and timestamp of its last modification.")
print("2. If you know the exact string or function name that disappeared or broke, run 'git log -S \"function_name\" --oneline'. This searches the commit history for instances where that specific string was added or removed.")

print("--------------------------------------------------------------")
print("Scenario 17: Handling Large Binary Assets Efficiently")
print("--------------------------------------------------------------")
print("Question: Your development team is adding large image assets, video tutorials, and compiled binaries (.zip, .exe) directly into the Git repository. The repository size has ballooned to several gigabytes, making 'git clone' commands painfully slow for new CI/CD pipelines. How do you resolve this?")
print("Answer:")
print("1. Install Git LFS on your system and initialize it in the repo using 'git lfs install'.")
print("2. Configure Git LFS to track specific large file extensions by running 'git lfs track \"*.mp4\"' or 'git lfs track \"*.zip\"'. This creates or updates a '.gitattributes' file.")
print("3. Commit the '.gitattributes' file. Moving forward, Git will only store tiny text pointers inside the repository, while the actual heavy binary payloads are stored on a separate, dedicated LFS object store.")

print("--------------------------------------------------------------")
print("Scenario 18: Syncing a Forked Repository with Upstream Changes")
print("--------------------------------------------------------------")
print("Question: You forked an open-source enterprise tool's repository into your organization's GitHub space six months ago. The original ('upstream') repository has received hundreds of security patches and features since then, and your fork is completely out of date. How do you sync your fork?")
print("Answer:")
print("1. Check your current remotes with 'git remote -v'.")
print("2. Add the original repository as a new remote called upstream: 'git remote add upstream <original_repo_URL>'.")
print("3. Fetch all branches from the upstream source: 'git fetch upstream'.")
print("4. Switch to your local main branch ('git checkout main') and merge the changes: 'git merge upstream/main'. Finally, push the updates to your own fork with 'git push origin main'.")

print("--------------------------------------------------------------")
print("Scenario 19: Aborting a Failed or Messy Merge Mid-Way")
print("--------------------------------------------------------------")
print("Question: You ran 'git merge feature-branch' into your staging branch. Git hit you with over 50 complex merge conflicts across various legacy code files. Realising you aren't prepared to resolve these right now, you want to completely undo the merge attempt and return your workspace to exactly how it looked a minute ago. How do you safely back out?")
print("Answer:")
print("1. Simply run the command 'git merge --abort'.")
print("2. Git will instantly stop the merge state, clean up all insertion markers from your files, and reset your working directory and staging area back to the pre-merge commit state. (Note: This only works if you haven't committed the conflict resolutions yet).")

print("--------------------------------------------------------------")
print("Scenario 20: The 'Sneak Peek' Fetch vs. Pull")
print("--------------------------------------------------------------")
print("Question: Your CI/CD deployment pipeline failed on a remote server. You suspect a teammate pushed a broken configuration change to the remote repository, but you don't want to bring their experimental code directly into your local working directory yet because it might break your local builds. How do you inspect their remote changes safely?")
print("Answer:")
print("1. Run 'git fetch origin'. This downloads all the latest commits, branches, and tags from the remote server into your local '.git' directory but does not touch your active working files.")
print("2. Inspect the differences by running 'git log main..origin/main' or 'git diff main origin/main'.")
print("3. Once you verify the changes are safe, you can then safely execute 'git merge origin/main' (or run 'git pull' to complete the sync).")
